# Generated by Django 5.2.8 on 2026-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_memo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.CharField(choices=[('university', 'University-wide'), ('department', 'Departmental'), ('personal', 'Personal/Individual')], default='department', max_length=20),
        ),
    ]
