# Generated by Django 6.0.4 on 2026-05-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_campus_department_is_college_department_campus'),
        ('memos', '0004_memo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='memo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='accounts.department'),
        ),
    ]
