# Generated by Django 6.0.4 on 2026-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0005_memo_campus_memo_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
