# Generated by Django 6.0.4 on 2026-05-07 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_role'),
        ('memos', '0006_memo_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memo',
            name='memos_memo_assigne_40d889_idx',
        ),
        migrations.AddField(
            model_name='memo',
            name='employees',
            field=models.ManyToManyField(related_name='memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='memos_memo_date_c1e7ac_idx'),
        ),
        migrations.RemoveField(
            model_name='memo',
            name='assigned_user',
        ),
    ]
