# Generated by Django 6.0.4 on 2026-05-07 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0007_remove_memo_memos_memo_assigne_40d889_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memo',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='memos', to=settings.AUTH_USER_MODEL),
        ),
    ]
