# Generated by Django 5.2.8 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0008_memo_to_all_alter_memo_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
    ]
