# Generated by Django 5.2.8 on 2026-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0009_alter_memo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='memo_requests/'),
        ),
    ]
