# Generated by Django 5.2.8 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0010_memo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
