# Generated by Django 5.2.8 on 2026-05-08 11:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0011_alter_memo_date_alter_memo_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='document',
        ),
        migrations.AlterField(
            model_name='memo',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 6, 51, 210427)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 6, 51, 211934)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='memo_requests/')),
                ('note', models.TextField(blank=True, help_text='Optional note from the requester')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='memos.memo')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
