# Generated by Django 5.2.8 on 2026-05-25 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260508_1005'),
        ('memos', '0012_remove_memo_document_alter_memo_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('target_participants', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objectives', models.TextField()),
                ('expected_outcomes', models.TextField()),
                ('doc_number', models.CharField(default='SNSU-F-AD-01', max_length=50)),
                ('rev_number', models.CharField(default='00', max_length=10)),
                ('effectivity_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL)),
                ('memo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_design', to='memos.memo')),
                ('noted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noted_activities', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_participants', models.PositiveIntegerField()),
                ('actual_budget_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary_of_outcomes', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_report', to='memos.activitydesign')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('created', 'Created'), ('forwarded', 'Forwarded'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released')], max_length=20)),
                ('date_tracked', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_actions', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='memos.memo')),
            ],
        ),
        migrations.CreateModel(
            name='InterCampusMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_director_approved', models.BooleanField(default=False)),
                ('recipient_director_approved', models.BooleanField(default=False)),
                ('memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inter_campus_details', to='memos.memo')),
                ('recipient_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inter_campus_memos', to='accounts.campus')),
                ('sender_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inter_campus_memos', to='accounts.campus')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLevelApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('draft', 'Draft'), ('dept_head', 'Department Head'), ('dean', 'Dean/Director'), ('vp', 'VP'), ('president', 'President'), ('released', 'Released')], default='draft', max_length=20)),
                ('dept_head_approved', models.BooleanField(default=False)),
                ('dean_approved', models.BooleanField(default=False)),
                ('vp_approved', models.BooleanField(default=False)),
                ('president_approved', models.BooleanField(default=False)),
                ('memo_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='memos.memorequest')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('transportation_mode', models.CharField(max_length=100)),
                ('estimated_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept_head_approved', models.BooleanField(default=False)),
                ('campus_director_approved', models.BooleanField(default=False)),
                ('doc_number', models.CharField(default='SNSU-F-TO-01', max_length=50)),
                ('rev_number', models.CharField(default='00', max_length=10)),
                ('effectivity_date', models.DateField(default=django.utils.timezone.now)),
                ('memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_order', to='memos.memo')),
            ],
        ),
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_liquidation_details', models.TextField()),
                ('accomplishments', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_report', to='memos.travelorder')),
            ],
        ),
    ]
