# Generated by Django 5.2.8 on 2026-05-04 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('congestion', 'Congestion Level'), ('utilization', 'Venue Utilization'), ('conflict_rate', 'Conflict Rate'), ('demand', 'Demand Index')], max_length=20)),
                ('value', models.FloatField()),
                ('reference_date', models.DateField(default=django.utils.timezone.now)),
                ('context_data', models.JSONField(blank=True, help_text='Extra data like department ID or venue ID.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reference_date', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingRiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=10)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('contributing_factors', models.TextField(help_text='Reasoning for the risk level.')),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
