# Generated by Django 5.2.8 on 2026-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_campus_department_is_college_department_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='school_id',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('instructor', 'Employee'), ('approver', 'Department Head/Approver'), ('transportation', 'Transportation'), ('staff', 'Staff')], default='instructor', max_length=20),
        ),
    ]
