# Generated by Django 6.0.4 on 2026-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_campus_department_is_college_department_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('instructor', 'Instructor'), ('approver', 'Department Head/Approver'), ('transportation', 'Transportation'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
