# Generated by Django 6.0.4 on 2026-05-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_role'),
        ('accounts', '0006_rename_school_id_profile_employee_id_profile_address_and_more'),
    ]

    operations = [
    ]
