# Generated by Django 5.2.8 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260508_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('instructor', 'Employee'), ('approver', 'Department Head/Approver'), ('transportation', 'Transportation'), ('staff', 'Staff')], default='instructor', max_length=20),
        ),
    ]
