# Generated by Django 6.0.4 on 2026-05-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260508_0953'),
        ('accounts', '0008_alter_profile_role'),
    ]

    operations = [
    ]
