# Generated by Django 5.2.8 on 2026-03-30 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_booking', to='memos.memo')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resources.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle'], name='resources_v_vehicle_4c167e_idx')],
            },
        ),
    ]
