# Generated by Django 6.0.4 on 2026-05-04 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('venue', 'Venue'), ('equipment', 'Equipment'), ('other', 'Other')], default='venue', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='memos.memo')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resources.resource')),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'memo'], name='resources_r_resourc_a9a40f_idx')],
            },
        ),
    ]
