# Generated by Django 5.2.8 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_resourcebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for vehicle use'),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of vehicle use', null=True),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of vehicle use', null=True),
        ),
    ]
