# Generated by Django 5.2.8 on 2026-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_vehiclebooking_days_vehiclebooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
